# Generated by Django 5.2.13 on 2026-05-24 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userdetails_address_userdetails_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='User',
            new_name='user',
        ),
        migrations.CreateModel(
            name='VendorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RestaurentName', models.CharField(max_length=100)),
                ('LICNo', models.CharField(max_length=100)),
                ('GSTNo', models.CharField(max_length=100)),
                ('LIC_Certificate', models.ImageField(upload_to='lic_certi/')),
                ('Restaurent_email', models.EmailField(max_length=100)),
                ('Restaurent_phone', models.IntegerField()),
                ('Restaurent_address', models.CharField(max_length=100)),
                ('landmark', models.CharField(max_length=100)),
                ('zipcode', models.IntegerField()),
                ('Restaurent_img', models.ImageField(upload_to='restimg/')),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
