# Generated by Django 5.2.13 on 2026-05-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('VEG', 'veg'), ('NONVEG', 'nonveg')], max_length=100)),
                ('price', models.IntegerField()),
                ('foodimg', models.ImageField(blank=None, null=None, upload_to='foodimg/')),
                ('Qty', models.CharField(max_length=100)),
            ],
        ),
    ]
