# Generated by Django 5.2.13 on 2026-07-09 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_user_userdetails_user_vendordetails'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.vendordetails'),
        ),
        migrations.AlterField(
            model_name='foodmenu',
            name='foodimg',
            field=models.ImageField(upload_to='foodimg/'),
        ),
    ]
