# Generated by Django 5.2.13 on 2026-07-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_foodmenu_restaurant_alter_foodmenu_foodimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
